### ISSUE TITLE
Unable to reproduce VAE-GAN results on CelebA

### ISSUE THREAD

**Issue by akshaykulkarni07** [prescient-design/CBGM#1]
Hi, congratulations on your great work and acceptance to ICLR.

I was trying to reproduce the baseline VAE-GAN on CelebA but it seems that the results at the end of 50 epochs of training (with the given config file) are not as expected. See below for screenshots of 49_latent.png (generated image from sampled latent) and 49.png (generated image from real latent). There is some kind of mode collapse there, could you please advise on how to fix this?

![49_latent](https://github.com/prescient-design/CBGM/assets/25796160/25a516c1-9372-453f-a9a0-8c65e1098d45)
![49](https://github.com/prescient-design/CBGM/assets/25796160/77852717-9d7f-4067-9069-89c8e398fe0d)

**Comment by k-eato** [comment]
Hello, I am experiencing this same problem, though in my case image quality is even worse. Any advice on what may be causing it would be greatly appreciated.

![image](https://github.com/prescient-design/CBGM/assets/29410997/2a552efc-7aa0-4c40-87d0-4c74c039a1bd)

**Comment by adebayoj** [comment]
Hi @k-eato and @akshaykulkarni07. Thanks for this comment and raising this point! Apologies for our tardiness in replying to you. We just noticed this issue. We'll replicate this and get back to you. We are also working on a revamp of the code and release some of the other model classes in the paper.

**Comment by akshaykulkarni07** [comment]
Hi @adebayoj, Thanks for your reply. Since the code has some issues, would it be possible for you to release the pretrained checkpoints/weights for the baseline VAE-GAN and the CB-VAE-GAN for CelebA?

**Comment by adebayoj** [comment]
Yes, this is definitely possible. Unfortunately, we'll have to go through some internal/legal approval to release model weights, which can actually take sometime. We are thinking of the quickest way to do that. We also want to debug the source of the issue to correct the problem.  Thanks for the patience, we'll get to the bottom of this.

**Comment by ismaia11** [comment]
Sorry for the late response; basically, you need to calculate FID as you go and take the best one while you train. I added the code to support this. The more samples you generate when you calculate FID the better the quality of your checkpoint is. I also changed the config files a bit
